module.exports={
    ticketKey:'ticket',
    loginEvent:'loginEvent',
    loadedEvent:'loaded',
    loadedFailEvent:'loadedFail',
    listLoadEvent:'listLoadEvent',
    formErrorEvent:'formErrorEvent',
    loginOutEvent:'login-out'
}